### ISSUE TITLE
declare var rand line 125

### ISSUE THREAD

**Issue by gfcannon12** [Alexaustin12/household-bot-training#2]
`var rand = Math.floor(Math.random() * roommates.length)`
I assume your code is working fine without making this "fix."  This is my way of proving to you that I read your your script.  Good stuff, man.

**Comment by Alexaustin12** [comment]
Ahh nice, yep it still works, but thanks for flagging / reviewing

**Comment by Alexaustin12** [comment]
Issue is resolved.
